### ISSUE TITLE
Fix forgot password form

### ISSUE THREAD

**Issue by aknuds1** [muzhack/muzhack#28]
Forgot password on staging server currently fails due to invalid SMTP password by the looks of it:

`2015-05-07 10:47:11.165 debug:  [Mail]  SMTP server URL: 'smtp://arve.knudsen%40gmail.com:dK-igz765FmK8KKrry1-Gg@smtp.mandrillapp.com:587'
2015-05-07 10:47:11.172 debug:  [Populate]  Found a license: cc-by-sa-3.0
Exception while invoking method 'forgotPassword' AuthError: Invalid login - 435 4.7.8 Error: authentication failed:
    at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:398:15)
    at smtpSend (packages/email/email.js:76:1)
    at Object.Email.send (packages/email/email.js:153:1)
    at Object.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:421:1)
    at [object Object].Meteor.methods.forgotPassword (packages/accounts-password/password_server.js:365:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
    at SMTPClient._actionAUTHComplete (/built_app/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:826:23)
    at SMTPClient._onData (/built_app/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:329:29)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickCallback (node.js:448:13)`

**Comment by aknuds1** [comment]
Fixed.
